import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Urutan dikunci di sini, bukan diserahkan ke autogenerated: whitepaper dibaca
 * berurutan, dan urutan bab adalah bagian dari argumennya.
 *
 * Halaman produk berdiri sebagai kategori tersendiri di antara "Ekosistem" dan
 * "Arsitektur token" — pembaca yang baru mengenal empat pilar biasanya ingin
 * memeriksa satu produk secara mendalam sebelum masuk ke tokenomics.
 */
const sidebars: SidebarsConfig = {
  whitepaper: [
    "ringkasan",
    "latar-belakang",
    "rekam-jejak",
    "ekosistem",
    {
      type: "category",
      label: "Produk",
      collapsed: false,
      link: { type: "doc", id: "ekosistem" },
      items: [
        "produk/aidm",
        "produk/skemguard",
        "produk/film",
        "produk/idm-chain",
      ],
    },
    "arsitektur-token",
    "model-ekonomi",
    "teknologi",
    "roadmap",
    "kepatuhan",
    "tim",
    "lampiran",
    "riwayat-revisi",
  ],
};

export default sidebars;
