import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Urutan dikunci di sini, bukan diserahkan ke autogenerated: whitepaper dibaca
 * berurutan, dan urutan bab adalah bagian dari argumennya.
 */
const sidebars: SidebarsConfig = {
  whitepaper: [
    "ringkasan", "latar-belakang", "rekam-jejak", "ekosistem",
    "arsitektur-token", "model-ekonomi", "teknologi", "roadmap",
    "kepatuhan", "tim", "lampiran", "riwayat-revisi",
  ],
};

export default sidebars;
